title: Splunk Windows log source conditions
order: 20
backends:
  - splunk
  - splunkxml
  - splunkdm
logsources:
  windows-application:
    product: windows
    service: application
    conditions:
      source: 'WinEventLog:Application'
  windows-security:
    product: windows
    service: security
    conditions:
      source: 'WinEventLog:Security'
  windows-system:
    product: windows
    service: system
    conditions:
      source: 'WinEventLog:System'
  windows-sysmon:
    product: windows
    service: sysmon
    conditions:
      source: 'WinEventLog:Microsoft-Windows-Sysmon/Operational'
  windows-powershell:
    product: windows
    service: powershell
    conditions:
      source: 'WinEventLog:Microsoft-Windows-PowerShell/Operational'
  windows-classicpowershell:
    product: windows
    service: powershell-classic
    conditions:
      source: 'WinEventLog:Windows PowerShell'
  windows-taskscheduler:
    product: windows
    service: taskscheduler
    conditions:
      source: 'WinEventLog:Microsoft-Windows-TaskScheduler/Operational'
  windows-wmi:
    product: windows
    service: wmi
    conditions:
      source: 'WinEventLog:Microsoft-Windows-WMI-Activity/Operational'
  windows-dns-server:
    product: windows
    service: dns-server
    category: dns
    conditions:
      source: 'WinEventLog:DNS Server'
  windows-dns-server-audit:
    product: windows
    service: dns-server-audit
    conditions:
      source: 'WinEventLog:Microsoft-Windows-DNS-Server/Audit'
  windows-driver-framework:
    product: windows
    service: driver-framework
    conditions:
      source: 'WinEventLog:Microsoft-Windows-DriverFrameworks-UserMode/Operational'
  windows-ntlm:
    product: windows
    service: ntlm
    conditions:
      source: 'WinEventLog:Microsoft-Windows-NTLM/Operational'
  windows-dhcp:
    product: windows
    service: dhcp
    conditions:
      source: 'WinEventLog:Microsoft-Windows-DHCP-Server/Operational'
  windows-applocker:
    product: windows
    service: applocker
    conditions:
      source:
        - 'WinEventLog:Microsoft-Windows-AppLocker/MSI and Script'
        - 'WinEventLog:Microsoft-Windows-AppLocker/EXE and DLL'
        - 'WinEventLog:Microsoft-Windows-AppLocker/Packaged app-Deployment'
        - 'WinEventLog:Microsoft-Windows-AppLocker/Packaged app-Execution'
  windows-msexchange-management:
    product: windows
    service: msexchange-management
    conditions:
      source: 'WinEventLog:MSExchange Management'
  windows-printservice-admin:
    product: windows
    service: printservice-admin
    conditions:
      source: 'WinEventLog:Microsoft-Windows-PrintService/Admin'
  windows-printservice-operational:
    product: windows
    service: printservice-operational
    conditions:
      source: 'WinEventLog:Microsoft-Windows-PrintService/Operational'
  windows-smbclient-security:
    product: windows
    service: smbclient-security
    conditions:
      source: 'WinEventLog:Microsoft-Windows-SmbClient/Security'
fieldmappings:
  EventID: EventCode
