title: Azure Activity Logs mapping for Azure Log Analytics
order: 20
backends:
  - ala
  - ala-rule
fieldmappings:
  claims.name: Caller
  properties.message: OperationNameValue
  properties.eventCategory: CategoryValue
  resourceProviderName.value: ResourceProviderValue
