title: Splunk Windows index and EventID field mapping
order: 20
backends:
  - splunk
  - splunkxml
  - splunkdm
logsources:
  windows:
    product: windows
    index: windows
fieldmappings:
    EventID: EventCode
