name: signatures

on: [push, pull_request]

jobs:
  build:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu-latest
        include:
          - target: ubuntu-latest
            os: ubuntu-latest
            build-type: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: false

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.6'

    - name: Set up Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq parallel make git

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Build
      run: |
        make yara-docker version=yara-4.2.0 threads=4
        make yara-docker version=yara-4.2.1 threads=4
        make suricata-docker version=suricata-6.0.5 threads=4
        make sigma-docker version=sigma-0.20 threads=4
        make sigma-docker version=sigma-0.21 threads=4
        make yara-docker-build version=yara-4.2.0
        make yara-docker-bump-build source_version=yara-4.2.0 target_version=yara-4.2.1
        make suricata-docker-build version=suricata-6.0.5
        make suricata-docker-test version=suricata-6.0.5
        make sigma-docker-build version=sigma-0.20 threads=8
        make sigma-docker-bump-build source_version=sigma-0.20 target_version=sigma-0.21 threads=4
        make stats-init
        make stats-yara version=yara-4.2.0
        make stats-final
        make package

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: |
          build/**/*.tar.gz

# make sigma-download version=sigma-0.21
